### ISSUE TITLE
Method "FCMdd" leading to clusters with same medoids

### ISSUE THREAD

**Issue by bauer-alex** [emf-creaf/vegclust#3]
Dear authors,

we found a potential bug in `vegclustdist` when applying it with `method = "FCMdd"`. When running a clustering it happens not too seldomly (depending on the application) that different clusters get assigned the exact same observation as medoid. I would assume that the function is not explicitly intended to lead to such a result?
Below you can find two minimal examples with toy data, and a potential fix for the issue.
Both examples were run with vegclust 2.0.0 on R 4.1.2, and could be reproduced on different operating systems.

# Minimal example 1
```r
library(vegclust)

toy_data <- data.frame(x = c(0, 1, 1))
dist     <- proxy::dist(toy_data)

set.seed(1234)
clust <- vegclustdist(dist, mobileMemb = 2, method = "FCMdd")
print(clust$mobileCenters)
# [1] 2 2
```

# Minimal example 2
```r
toy_data2 <- data.frame(x = rnorm(10), y = rpois(10, lambda = 3))
dist2     <- proxy::dist(toy_data2)

set.seed(156)
clust2 <- vegclustdist(dist2, mobileMemb = 2, method = "FCMdd")
print(clust2$mobileCenters)
# [1] 7 7
```

# Potential fix
In [line 114 of vegclustdist.R](https://github.com/emf-creaf/vegclust/blob/9d3b31b2bacd1a0eb031f9fd7c78672c6cd769b2/R/vegclustdist.R#L114) new medoids are assigned. The issue seems that when searching a new medoid for cluster k the function evaluates all other observations as potential medoids, including the current medoids of other clusters. Instead, we would propose to exclude current medoids of other cluster from this updating step. The new code could look something like this:
```r
medoids_otherClusters = med[-k]
d_withoutOtherMedoids = d[,-medoids_otherClusters]
med[k] = as.numeric(colnames(d_withoutOtherMedoids)[which.min((u[, k]^m) %*% d_withoutOtherMedoids)])
dist2med[, k] = d[, med[k]]
```
In the above two examples this code prevents identical cluster medoids from being selected.
What do you think about this? If you want we could implement the code a bit more nicely (maybe also preventing observations to be chosen as medoids which are perfectly identical to current medoids of other clusters) and then do a pull request.

**Comment by miquelcaceres** [comment]
Thanks for reporting this issue. Now the code in vegclustdist reads:
```
candidates = 1:n
excluded = numeric(0)
# Exclude as candidates objects with membership 1 to other clusters as potential medoids for this cluster
excluded = which(apply(u[,-k, drop=FALSE], 1 ,max)==1.0)
if(length(excluded)>0) candidates = candidates[-excluded]
#Determine medoid
med[k] = candidates[which.min((u[, k]^m) %*% d[,candidates])]
dist2med[,k] = d[,med[k]]
```
This also prevents all observations with membership == 1 (the medoid or identical objects) to be chosen as new medoids. I also added a filter in the selection of seeds for random initial medoids to avoid seeds to be identical objects:
```
  x_mat = as.matrix(x)
  n = nrow(x_mat)
	if(is.null(seeds)) seeds = 	1:n
	# Exclude as potential seeds those objects that are at the same position as a previous objects
  toExclude = rep(FALSE, n)
  for(i in 2:n) {
    if(min(x_mat[i,1:(i-1)])==0) toExclude[i] = TRUE
  }
  seeds = seeds[!toExclude]
```

**Comment by bauer-alex** [comment]
Seems to resolve the issue, thanks!
